name: "@workflows/fun/fortune-teller"
version: 1.0.0
type: workflow
description: "Daily cosmic fortune"

files:
  main: fortune-teller.nika.yaml

metadata:
  author: SuperNovae
  license: MIT
  keywords: [nika, workflow, fun, fortune-teller]
  pattern: creative-generation
  category: fun
  git:
    date: 2026-02-23
