name: "@workflows/fun/weather-outfit"
version: 1.0.0
type: workflow
description: "Weather to outfit recommendation"

files:
  main: weather-outfit.nika.yaml

metadata:
  author: SuperNovae
  license: MIT
  keywords: [nika, workflow, fun, weather-outfit]
  pattern: fetch-infer
  category: fun
  git:
    date: 2026-02-23
